services:
  app-sistemas-ventas:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-sistemas-ventas:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
      - DB_PORT
      - DB_MAX
      - DB_IDLE_TIMEOUT
      - DB_SSL_REJECT_UNAUTHORIZED
      - NODE_ENV
    networks:
      - dev-network
    command: sh -c "npm run start"
    expose:
      - 3000

networks:
  dev-network:
    external: true
    