name: Build and deploy container app to Azure Web App - app-sistemas-ventas

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://appsistemasventas.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_020fb6b8b9644240b4248f55a7817801 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_843d90c9cff24eb589aa3412942141b5 }}
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: appsistemasventas.azurecr.io/app-sistemas-ventas:${{ github.sha }}  # ✅ Sin username/
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-sistemas-ventas'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1c98d33dc9ef41cf8b0fadff29c7f968 }}
        images: 'appsistemasventas.azurecr.io/app-sistemas-ventas:${{ github.sha }}'  # ✅ Sin username/